module.exports = {
  TESTING: {
    POSITION_MANAGER: {
      CLEAR_ON_STARTUP: false
    }
  },
  POSITION: {
    MAX_POSITIONS: 3
  },
  TRADER: {
    SAVE_INTERVAL: 60000, // 1 minute
    CLEANUP_INTERVAL: 3600000, // 1 hour
    INACTIVE_THRESHOLD: 604800000, // 7 days
    SUSPICIOUS_TRADE_INTERVAL: 1000, // 1 second
    SUSPICIOUS_ACTIVITY_RESET_INTERVAL: 86400000 // 24 hours
  },
  EXIT_STRATEGIES: {}
};
